<?php return array (
  'email_type' => '1',
  'email_safe' => '',
  'mail_address' => '',
  'smtp' => '',
  'smtp_user' => '',
  'smtp_pwd' => '',
  'smtp_port' => '',
  'order_by' => 'new',
  'name' => 'dieshi_shop',
  'url' => 'http://www.baidu.com',
  'master' => '',
  'qq' => '',
  'email' => '',
  'mobile' => '',
  'phone' => '',
  'address' => '',
  'site_footer_code' => '<div class="footer" style="text-align:center"><p class="links"><a href="">关于我们</a>|<a href="">常见问题</a></div>',
  'tax' => '10',
  'stockup_time' => '1',
  'index_seo_title' => 'iShop',
  'index_seo_keywords' => '商城系统',
  'index_seo_description' => 'ishop是基于php开发',
  'goods_no_pre' => 'SD',
  'commission' => '',
  'store_num_warning' => '1',
  'reg_option' => '0',
);